spring:
  application:
    name: EventoIngressosBackend

  config:
    import: "optional:file:.env[.properties]"

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-minutes: ${JWT_EXPIRATION_MINUTES:1440}

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    org.hibernate.SQL: ${SQL_LOG_LEVEL:info}
